name: CI - Lint, Type-check, and Test

on:
  push:
    branches:
      -main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff mypy pytest

      # ---- Ruff (Lint) ----
      - name: Lint with Ruff
        run: |
          ruff check .

      # ---- Mypy (Type Check) ----
      - name: Type check with Mypy
        run: |
          mypy src/

      # ---- Pytest (Unit Tests) ----
      - name: Run tests with Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
